export let employees = [
    {
      DOB: "1979-02-24",
      DOJ: "2018-03-21",
      CF1: "Customer Support",
      firstName: "Charlotte",
      lastName: "Johnson",
      name: "Charlotte Johnson",
      email: "charlotte.johnson@example.com",
      id: "krbstjo05i7wyn76mahqrq",
      job: "Operations Manager",
      initials: "CJ",
      department: "Product",
      workphone: "01724459861",
      // mobile: "01724251063",
      manager: "ethan.d@megazap.us",
      employeeid: "54",
      costcenter: "93",
      buildingid: "128",
      floorname: "JKL",
      floorsection: "central area",
      location: "115 JKL",
      address: "789 Pine Road",
      image: "https://example.com/image6.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1979-01-24",
      DOJ: "2021-01-06",
      CF1: "Legal",
      firstName: "Sophia",
      lastName: "Johnson",
      name: "Sophia Johnson",
      email: "sophia.johnson@example.com",
      id: "59oz9x71c0mjdbioiz2edn",
      // job: "HR Manager",
      initials: "SJ",
      department: "Sales",
      workphone: "01724603127",
      mobile: "01724982489",
      manager: "michael.s@megazap.us",
      employeeid: "14",
      costcenter: "38",
      buildingid: "111",
      floorname: "STU",
      floorsection: "north wing",
      location: "115 JKL",
      address: "123 Elm Street",
      image: "https://example.com/image6.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1979-06-19",
      DOJ: "2015-02-10",
      CF1: "Operations",
      firstName: "John",
      lastName: "Moore",
      name: "John Moore",
      email: "john.moore@example.com",
      id: "kslicbstaurlxf0w3unobg",
      job: "Product Manager",
      initials: "JM",
      department: "Operations",
      workphone: "01724943674",
      mobile: "01724447527",
      manager: "ethan.d@megazap.us",
      employeeid: "62",
      costcenter: "50",
      buildingid: "114",
      floorname: "JKL",
      floorsection: "north wing",
      location: "122 DEF",
      address: "123 Elm Street",
      image: "https://example.com/image1.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1977-07-28",
      DOJ: "2023-06-06",
      CF1: "Product",
      firstName: "Liam",
      lastName: "Smith",
      name: "Liam Smith",
      email: "liam.smith@example.com",
      id: "brgxbnqad3f2mka2x2o63y",
      job: "Product Manager",
      initials: "LS",
      department: "Product",
      workphone: "01724213509",
      mobile: "01724701542",
      manager: "ethan.d@megazap.us",
      employeeid: "97",
      costcenter: "92",
      buildingid: "123",
      floorname: "DEF",
      floorsection: "south area",
      location: "112 ABC",
      address: "123 Elm Street",
      image: "https://example.com/image8.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1980-09-14",
      DOJ: "2019-04-23",
      CF1: "Sales",
      firstName: "James",
      lastName: "Johnson",
      name: "James Johnson",
      email: "james.johnson@example.com",
      id: "qdc1rteakc9hisjo8lpzm",
      job: "Operations Manager",
      initials: "JJ",
      department: "HR",
      workphone: "01724294501",
      mobile: "01724638156",
      manager: "john.d@megazap.us",
      employeeid: "77",
      costcenter: "96",
      buildingid: "113",
      floorname: "JKL",
      floorsection: "north wing",
      location: "122 DEF",
      address: "456 Oak Avenue",
      image: "https://example.com/image4.jpg",
      gender: "Female",
      employmentType: "Full-Time",
    },
    {
      DOB: "1980-06-05",
      DOJ: "2023-03-22",
      CF1: "Sales",
      firstName: "Ethan",
      lastName: "Lee",
      name: "Ethan Lee",
      email: "ethan.lee@example.com",
      id: "uhjyfmzbyvlgor66uk9jk",
      job: "Accountant",
      initials: "EL",
      department: "Sales",
      workphone: "01724822439",
      mobile: "01724168186",
      manager: "emma.w@megazap.us",
      employeeid: "90",
      costcenter: "64",
      buildingid: "110",
      floorname: "DEF",
      floorsection: "north wing",
      location: "122 DEF",
      address: "202 Birch Lane",
      image: "https://example.com/image9.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1992-02-28",
      DOJ: "2014-04-01",
      CF1: "R&D",
      firstName: "Charlotte",
      lastName: "Lee",
      name: "Charlotte Lee",
      email: "charlotte.lee@example.com",
      id: "f8wolglptxtb6fzh2borq",
      job: "Marketing Specialist",
      initials: "CL",
      department: "Operations",
      workphone: "01724352971",
      mobile: "01724190791",
      manager: "emma.w@megazap.us",
      employeeid: "57",
      costcenter: "87",
      buildingid: "125",
      floorname: "VWX",
      floorsection: "central area",
      location: "117 PQR",
      address: "789 Pine Road",
      image: "https://example.com/image1.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1999-07-22",
      DOJ: "2011-01-11",
      CF1: "Customer Support",
      firstName: "James",
      lastName: "Moore",
      name: "James Moore",
      email: "james.moore@example.com",
      id: "38mfs880494pctjyikanv",
      job: "Legal Advisor",
      initials: "JM",
      department: "IT",
      workphone: "01724491108",
      mobile: "01724790952",
      manager: "ethan.d@megazap.us",
      employeeid: "30",
      costcenter: "12",
      buildingid: "120",
      floorname: "VWX",
      floorsection: "east wing",
      location: "115 JKL",
      address: "789 Pine Road",
      image: "https://example.com/image8.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1977-10-25",
      DOJ: "2024-04-26",
      CF1: "Legal",
      firstName: "Jane",
      lastName: "Brown",
      name: "Jane Brown",
      email: "jane.brown@example.com",
      id: "hn3htcarz047mnn60im4md",
      job: "Marketing Specialist",
      initials: "JB",
      department: "Legal",
      workphone: "01724968442",
      mobile: "01724983534",
      manager: "john.d@megazap.us",
      employeeid: "36",
      costcenter: "40",
      buildingid: "116",
      floorname: "ABC",
      floorsection: "east wing",
      location: "122 DEF",
      address: "123 Elm Street",
      image: "https://example.com/image7.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1974-04-12",
      DOJ: "2013-03-03",
      CF1: "Legal",
      firstName: "Jane",
      lastName: "Moore",
      name: "Jane Moore",
      email: "jane.moore@example.com",
      id: "bkcl3i631ebslh9aq75t0s",
      job: "Sales Executive",
      initials: "JM",
      department: "Marketing",
      workphone: "01724279304",
      mobile: "01724544581",
      manager: "susan.t@megazap.us",
      employeeid: "31",
      costcenter: "49",
      buildingid: "126",
      floorname: "MNO",
      floorsection: "west area",
      location: "122 DEF",
      address: "404 Willow Street",
      image: "https://example.com/image3.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1982-07-31",
      DOJ: "2012-02-10",
      CF1: "Customer Support",
      firstName: "Lucas",
      lastName: "Martinez",
      name: "Lucas Martinez",
      email: "lucas.martinez@example.com",
      id: "2s79oe0l8mfu201a0gtq9d",
      job: "Legal Advisor",
      initials: "LM",
      department: "Engineering",
      workphone: "01724445916",
      mobile: "01724297012",
      manager: "ethan.d@megazap.us",
      employeeid: "34",
      costcenter: "20",
      buildingid: "112",
      floorname: "MNO",
      floorsection: "south area",
      location: "112 ABC",
      address: "123 Elm Street",
      image: "https://example.com/image1.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1972-09-07",
      DOJ: "2019-12-09",
      CF1: "Product",
      firstName: "Jane",
      lastName: "Brown",
      name: "Jane Brown",
      email: "jane.brown@example.com",
      id: "r9kps80g7ygcuw210dbjh",
      job: "Customer Support Specialist",
      initials: "JB",
      department: "IT",
      workphone: "01724574400",
      mobile: "01724379995",
      manager: "susan.t@megazap.us",
      employeeid: "41",
      costcenter: "68",
      buildingid: "113",
      floorname: "VWX",
      floorsection: "south area",
      location: "112 ABC",
      address: "101 Maple Street",
      image: "https://example.com/image2.jpg",
      gender: "Male",
      employmentType: "Full-Time",
    },
    {
      DOB: "1976-12-15",
      DOJ: "2024-04-22",
      CF1: "HR",
      firstName: "Sophia",
      lastName: "Lee",
      name: "Sophia Lee",
      email: "sophia.lee@example.com",
      id: "2lc6b1zty7n4gd35zikx7l",
      job: "Accountant",
      initials: "SL",
      department: "Marketing",
      workphone: "01724267973",
      mobile: "01724332499",
      manager: "olivia.b@megazap.us",
      employeeid: "32",
      costcenter: "17",
      buildingid: "111",
      floorname: "DEF",
      floorsection: "west area",
      location: "115 JKL",
      address: "123 Elm Street",
      image: "https://example.com/image2.jpg",
      gender: "Female",
      employmentType: "Full-Time",
    },
    {
      DOB: "1988-03-09",
      DOJ: "2014-04-24",
      CF1: "Marketing",
      firstName: "Olivia",
      lastName: "Williams",
      name: "Olivia Williams",
      email: "olivia.williams@example.com",
      id: "8dw6jlm7iuxq0rk5t5xg",
      job: "Marketing Specialist",
      initials: "OW",
      department: "Legal",
      workphone: "01724276346",
      mobile: "01724928852",
      manager: "olivia.b@megazap.us",
      employeeid: "29",
      costcenter: "93",
      buildingid: "117",
      floorname: "ABC",
      floorsection: "central area",
      location: "112 ABC",
      address: "456 Oak Avenue",
      image: "https://example.com/image7.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1996-01-25",
      DOJ: "2022-01-07",
      CF1: "HR",
      firstName: "Charlotte",
      lastName: "Moore",
      name: "Charlotte Moore",
      email: "charlotte.moore@example.com",
      id: "vutxilgujqjvsc0bqsea",
      job: "Operations Manager",
      initials: "CM",
      department: "HR",
      workphone: "01724524251",
      mobile: "01724321254",
      manager: "emma.w@megazap.us",
      employeeid: "22",
      costcenter: "14",
      buildingid: "119",
      floorname: "ABC",
      floorsection: "north wing",
      location: "117 PQR",
      address: "101 Maple Street",
      image: "https://example.com/image6.jpg",
      gender: "Female",
      employmentType: "Full-Time",
    },
    {
      DOB: "1971-08-07",
      DOJ: "2011-08-05",
      CF1: "Sales",
      firstName: "Olivia",
      lastName: "Brown",
      name: "Olivia Brown",
      email: "olivia.brown@example.com",
      id: "fpjfyoj6ui5c2xnup46h14",
      job: "Marketing Specialist",
      initials: "OB",
      department: "Marketing",
      workphone: "01724140329",
      mobile: "01724714983",
      manager: "susan.t@megazap.us",
      employeeid: "64",
      costcenter: "88",
      buildingid: "111",
      floorname: "GHI",
      floorsection: "east wing",
      location: "112 ABC",
      address: "404 Willow Street",
      image: "https://example.com/image10.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1980-09-10",
      DOJ: "2022-07-16",
      CF1: "Engineering",
      firstName: "Michael",
      lastName: "Smith",
      name: "Michael Smith",
      email: "michael.smith@example.com",
      id: "914s5grboyae4x7c5ycgfs",
      job: "Accountant",
      initials: "MS",
      department: "R&D",
      workphone: "01724203662",
      mobile: "01724540738",
      manager: "james.j@megazap.us",
      employeeid: "32",
      costcenter: "83",
      buildingid: "113",
      floorname: "GHI",
      floorsection: "west area",
      location: "121 ABC",
      address: "123 Elm Street",
      image: "https://example.com/image4.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1991-10-05",
      DOJ: "2015-02-04",
      CF1: "Operations",
      firstName: "Emma",
      lastName: "Garcia",
      name: "Emma Garcia",
      email: "emma.garcia@example.com",
      id: "qffwmnx7gobdgoprp75nu5",
      job: "HR Manager",
      initials: "EG",
      department: "Engineering",
      workphone: "01724197171",
      mobile: "01724166639",
      manager: "susan.t@megazap.us",
      employeeid: "18",
      costcenter: "86",
      buildingid: "126",
      floorname: "JKL",
      floorsection: "south area",
      location: "114 GHI",
      address: "101 Maple Street",
      image: "https://example.com/image7.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1995-01-31",
      DOJ: "2014-10-28",
      CF1: "Sales",
      firstName: "Michael",
      lastName: "Smith",
      name: "Michael Smith",
      email: "michael.smith@example.com",
      id: "h7jzhk6nh3rt63i3lyvhld",
      job: "Accountant",
      initials: "MS",
      department: "Finance",
      workphone: "01724846900",
      mobile: "01724208597",
      manager: "michael.s@megazap.us",
      employeeid: "31",
      costcenter: "15",
      buildingid: "115",
      floorname: "MNO",
      floorsection: "central area",
      location: "120 YZ",
      address: "303 Cedar Avenue",
      image: "https://example.com/image11.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1982-02-01",
      DOJ: "2011-08-15",
      CF1: "Sales",
      firstName: "Jane",
      lastName: "Lee",
      name: "Jane Lee",
      email: "jane.lee@example.com",
      id: "ftd9ukgzwpoqsmqimz3rfq",
      job: "Product Manager",
      initials: "JL",
      department: "Customer Support",
      workphone: "01724373806",
      mobile: "01724287878",
      manager: "john.d@megazap.us",
      employeeid: "87",
      costcenter: "13",
      buildingid: "118",
      floorname: "GHI",
      floorsection: "north wing",
      location: "112 ABC",
      address: "202 Birch Lane",
      image: "https://example.com/image4.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1998-06-01",
      DOJ: "2014-03-12",
      CF1: "Finance",
      firstName: "Ethan",
      lastName: "Garcia",
      name: "Ethan Garcia",
      email: "ethan.garcia@example.com",
      id: "7jjnrq0o8fjyq0n1v7kho",
      job: "Marketing Specialist",
      initials: "EG",
      department: "Sales",
      workphone: "01724424648",
      mobile: "01724734898",
      manager: "emma.w@megazap.us",
      employeeid: "32",
      costcenter: "21",
      buildingid: "121",
      floorname: "VWX",
      floorsection: "north wing",
      location: "121 ABC",
      address: "606 Redwood Boulevard",
      image: "https://example.com/image8.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1970-08-20",
      DOJ: "2019-01-08",
      CF1: "Engineering",
      firstName: "Olivia",
      lastName: "Smith",
      name: "Olivia Smith",
      email: "olivia.smith@example.com",
      id: "i2rhsgqpkbsepszjth14b",
      job: "Research Analyst",
      initials: "OS",
      department: "HR",
      workphone: "01724188676",
      mobile: "01724577346",
      manager: "emma.w@megazap.us",
      employeeid: "37",
      costcenter: "30",
      buildingid: "122",
      floorname: "JKL",
      floorsection: "east wing",
      location: "112 ABC",
      address: "505 Spruce Drive",
      image: "https://example.com/image5.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1978-10-16",
      DOJ: "2014-12-29",
      CF1: "Legal",
      firstName: "John",
      lastName: "Johnson",
      name: "John Johnson",
      email: "john.johnson@example.com",
      id: "bpmmpxow8wdga4onbmmu6u",
      job: "Research Analyst",
      initials: "JJ",
      department: "IT",
      workphone: "01724402356",
      mobile: "01724990642",
      manager: "james.j@megazap.us",
      employeeid: "16",
      costcenter: "92",
      buildingid: "127",
      floorname: "MNO",
      floorsection: "east wing",
      location: "117 PQR",
      address: "101 Maple Street",
      image: "https://example.com/image3.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1991-04-19",
      DOJ: "2013-11-06",
      CF1: "Legal",
      firstName: "Mia",
      lastName: "Miller",
      name: "Mia Miller",
      email: "mia.miller@example.com",
      id: "ok4k1yu7zvo18yesnecxl",
      job: "Engineer",
      initials: "MM",
      department: "Legal",
      workphone: "01724240333",
      mobile: "01724350160",
      manager: "susan.t@megazap.us",
      employeeid: "41",
      costcenter: "55",
      buildingid: "111",
      floorname: "DEF",
      floorsection: "east wing",
      location: "114 GHI",
      address: "808 Ash Avenue",
      image: "https://example.com/image11.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1981-08-07",
      DOJ: "2010-12-04",
      CF1: "R&D",
      firstName: "Lucas",
      lastName: "Davis",
      name: "Lucas Davis",
      email: "lucas.davis@example.com",
      id: "htnt9dtedrdjw89ibc5hu",
      job: "Operations Manager",
      initials: "LD",
      department: "Customer Support",
      workphone: "01724973044",
      mobile: "01724316312",
      manager: "james.j@megazap.us",
      employeeid: "64",
      costcenter: "66",
      buildingid: "122",
      floorname: "GHI",
      floorsection: "south area",
      location: "122 DEF",
      address: "101 Maple Street",
      image: "https://example.com/image10.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1983-10-17",
      DOJ: "2012-01-23",
      CF1: "Sales",
      firstName: "Charlotte",
      lastName: "Lee",
      name: "Charlotte Lee",
      email: "charlotte.lee@example.com",
      id: "3sa3m5fent96w2msl882qi",
      job: "Product Manager",
      initials: "CL",
      department: "R&D",
      workphone: "01724768575",
      mobile: "01724883416",
      manager: "james.j@megazap.us",
      employeeid: "49",
      costcenter: "89",
      buildingid: "117",
      floorname: "DEF",
      floorsection: "west area",
      location: "120 YZ",
      address: "789 Pine Road",
      image: "https://example.com/image11.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "2000-05-27",
      DOJ: "2017-09-04",
      CF1: "Customer Support",
      firstName: "Lucas",
      lastName: "Brown",
      name: "Lucas Brown",
      email: "lucas.brown@example.com",
      id: "49hlj9v8s8rs7bdwdu2r4",
      job: "Customer Support Specialist",
      initials: "LB",
      department: "Sales",
      workphone: "01724737663",
      mobile: "01724418446",
      manager: "ethan.d@megazap.us",
      employeeid: "90",
      costcenter: "96",
      buildingid: "124",
      floorname: "JKL",
      floorsection: "east wing",
      location: "117 PQR",
      address: "505 Spruce Drive",
      image: "https://example.com/image1.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1978-06-28",
      DOJ: "2013-06-18",
      CF1: "Legal",
      firstName: "Emma",
      lastName: "Brown",
      name: "Emma Brown",
      email: "emma.brown@example.com",
      id: "tilhebobzaa03t32yhxucgc",
      job: "Research Analyst",
      initials: "EB",
      department: "Legal",
      workphone: "01724168866",
      mobile: "01724684313",
      manager: "olivia.b@megazap.us",
      employeeid: "62",
      costcenter: "64",
      buildingid: "128",
      floorname: "STU",
      floorsection: "west area",
      location: "114 GHI",
      address: "505 Spruce Drive",
      image: "https://example.com/image8.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1982-05-13",
      DOJ: "2019-12-01",
      CF1: "IT",
      firstName: "John",
      lastName: "Miller",
      name: "John Miller",
      email: "john.miller@example.com",
      id: "ti8fmka37ggir7q7pdba7",
      job: "Operations Manager",
      initials: "JM",
      department: "R&D",
      workphone: "01724111632",
      mobile: "01724639201",
      manager: "olivia.b@megazap.us",
      employeeid: "75",
      costcenter: "73",
      buildingid: "121",
      floorname: "JKL",
      floorsection: "west area",
      location: "114 GHI",
      address: "456 Oak Avenue",
      image: "https://example.com/image10.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1993-05-22",
      DOJ: "2012-05-04",
      CF1: "Marketing",
      firstName: "Jane",
      lastName: "Garcia",
      name: "Jane Garcia",
      email: "jane.garcia@example.com",
      id: "2c6rz92i0rd63g1i9i48m5",
      job: "IT Support Specialist",
      initials: "JG",
      department: "R&D",
      workphone: "01724372099",
      mobile: "01724690274",
      manager: "james.j@megazap.us",
      employeeid: "70",
      costcenter: "50",
      buildingid: "117",
      floorname: "VWX",
      floorsection: "central area",
      location: "122 DEF",
      address: "789 Pine Road",
      image: "https://example.com/image4.jpg",
      gender: "Female",
      employmentType: "Full-Time",
    },
    {
      DOB: "1970-06-23",
      DOJ: "2016-09-27",
      CF1: "IT",
      firstName: "John",
      lastName: "Smith",
      name: "John Smith",
      email: "john.smith@example.com",
      id: "gmogzz9a5nqcbjcyisn8",
      job: "Sales Executive",
      initials: "JS",
      department: "Engineering",
      workphone: "01724981229",
      mobile: "01724281703",
      manager: "ethan.d@megazap.us",
      employeeid: "77",
      costcenter: "40",
      buildingid: "128",
      floorname: "ABC",
      floorsection: "east wing",
      location: "115 JKL",
      address: "789 Pine Road",
      image: "https://example.com/image10.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1986-04-09",
      DOJ: "2019-02-27",
      CF1: "Finance",
      firstName: "Olivia",
      lastName: "Garcia",
      name: "Olivia Garcia",
      email: "olivia.garcia@example.com",
      id: "ekbbxeiy4psdrez9djan",
      job: "Research Analyst",
      initials: "OG",
      department: "Operations",
      workphone: "01724576928",
      mobile: "01724666635",
      manager: "michael.s@megazap.us",
      employeeid: "32",
      costcenter: "13",
      buildingid: "123",
      floorname: "GHI",
      floorsection: "west area",
      location: "114 GHI",
      address: "808 Ash Avenue",
      image: "https://example.com/image6.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1999-08-23",
      DOJ: "2024-04-16",
      CF1: "Legal",
      firstName: "Sophia",
      lastName: "Lee",
      name: "Sophia Lee",
      email: "sophia.lee@example.com",
      id: "5yevw4mo3tfw4o857zmhd",
      job: "Product Manager",
      initials: "SL",
      department: "HR",
      workphone: "01724401951",
      mobile: "01724965651",
      manager: "james.j@megazap.us",
      employeeid: "94",
      costcenter: "26",
      buildingid: "112",
      floorname: "YZ",
      floorsection: "west area",
      location: "121 ABC",
      address: "202 Birch Lane",
      image: "https://example.com/image7.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1990-10-14",
      DOJ: "2021-05-01",
      CF1: "R&D",
      firstName: "Emma",
      lastName: "Moore",
      name: "Emma Moore",
      email: "emma.moore@example.com",
      id: "64h3715r0bsrskr6wqi3pa",
      job: "Engineer",
      initials: "EM",
      department: "Operations",
      workphone: "01724923107",
      mobile: "01724400823",
      manager: "john.d@megazap.us",
      employeeid: "66",
      costcenter: "63",
      buildingid: "111",
      floorname: "PQR",
      floorsection: "south area",
      location: "114 GHI",
      address: "456 Oak Avenue",
      image: "https://example.com/image7.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1977-02-04",
      DOJ: "2011-08-30",
      CF1: "Legal",
      firstName: "Lucas",
      lastName: "Garcia",
      name: "Lucas Garcia",
      email: "lucas.garcia@example.com",
      id: "0fw4otzcre29xhol22h25x",
      job: "Sales Executive",
      initials: "LG",
      department: "Product",
      workphone: "01724892144",
      mobile: "01724575669",
      manager: "emma.w@megazap.us",
      employeeid: "53",
      costcenter: "97",
      buildingid: "117",
      floorname: "VWX",
      floorsection: "south area",
      location: "122 DEF",
      address: "707 Fir Street",
      image: "https://example.com/image1.jpg",
      gender: "Female",
      employmentType: "Part-Time",
    },
    {
      DOB: "1987-07-15",
      DOJ: "2017-01-05",
      CF1: "Legal",
      firstName: "Olivia",
      lastName: "Brown",
      name: "Olivia Brown",
      email: "olivia.brown@example.com",
      id: "6zzelp1i5stiigca83sji",
      job: "HR Manager",
      initials: "OB",
      department: "Sales",
      workphone: "01724196126",
      mobile: "01724361594",
      manager: "ethan.d@megazap.us",
      employeeid: "10",
      costcenter: "86",
      buildingid: "116",
      floorname: "ABC",
      floorsection: "west area",
      location: "114 GHI",
      address: "505 Spruce Drive",
      image: "https://example.com/image10.jpg",
      gender: "Female",
      employmentType: "Full-Time",
    },
    {
      DOB: "1996-08-08",
      DOJ: "2016-05-01",
      CF1: "Legal",
      firstName: "Ava",
      lastName: "Miller",
      name: "Ava Miller",
      email: "ava.miller@example.com",
      id: "4ewilt62v854xt3yj36kut",
      job: "Marketing Specialist",
      initials: "AM",
      department: "Engineering",
      workphone: "01724341491",
      mobile: "01724488450",
      manager: "emma.w@megazap.us",
      employeeid: "47",
      costcenter: "60",
      buildingid: "111",
      floorname: "JKL",
      floorsection: "south area",
      location: "120 YZ",
      address: "808 Ash Avenue",
      image: "https://example.com/image2.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1999-03-28",
      DOJ: "2022-12-07",
      CF1: "IT",
      firstName: "Ava",
      lastName: "Lee",
      name: "Ava Lee",
      email: "ava.lee@example.com",
      id: "96c3anpvvz4qrk6lpbm66",
      job: "HR Manager",
      initials: "AL",
      department: "Finance",
      workphone: "01724813734",
      mobile: "01724760883",
      manager: "john.d@megazap.us",
      employeeid: "31",
      costcenter: "32",
      buildingid: "116",
      floorname: "ABC",
      floorsection: "south area",
      location: "117 PQR",
      address: "456 Oak Avenue",
      image: "https://example.com/image5.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1990-06-20",
      DOJ: "2014-01-01",
      CF1: "Legal",
      firstName: "Sophia",
      lastName: "Moore",
      name: "Sophia Moore",
      email: "sophia.moore@example.com",
      id: "9nby29uzx3pxs9937o015",
      job: "Customer Support Specialist",
      initials: "SM",
      department: "Sales",
      workphone: "01724778894",
      mobile: "01724676194",
      manager: "ethan.d@megazap.us",
      employeeid: "55",
      costcenter: "11",
      buildingid: "117",
      floorname: "ABC",
      floorsection: "central area",
      location: "121 ABC",
      address: "404 Willow Street",
      image: "https://example.com/image3.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1984-08-04",
      DOJ: "2020-03-16",
      CF1: "HR",
      firstName: "Michael",
      lastName: "Williams",
      name: "Michael Williams",
      email: "michael.williams@example.com",
      id: "fwzyfl2678fz90vmahmpi",
      job: "Legal Advisor",
      initials: "MW",
      department: "Marketing",
      workphone: "01724681024",
      mobile: "01724148363",
      manager: "john.d@megazap.us",
      employeeid: "76",
      costcenter: "58",
      buildingid: "122",
      floorname: "VWX",
      floorsection: "central area",
      location: "117 PQR",
      address: "808 Ash Avenue",
      image: "https://example.com/image8.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1984-11-11",
      DOJ: "2010-10-21",
      CF1: "HR",
      firstName: "Michael",
      lastName: "Lee",
      name: "Michael Lee",
      email: "michael.lee@example.com",
      id: "xpll8adpuov7zyoxnsg9",
      job: "Legal Advisor",
      initials: "ML",
      department: "Product",
      workphone: "01724776708",
      mobile: "01724137275",
      manager: "ethan.d@megazap.us",
      employeeid: "26",
      costcenter: "99",
      buildingid: "111",
      floorname: "YZ",
      floorsection: "south area",
      location: "114 GHI",
      address: "123 Elm Street",
      image: "https://example.com/image3.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1990-09-09",
      DOJ: "2012-06-04",
      CF1: "HR",
      firstName: "Mia",
      lastName: "Martinez",
      name: "Mia Martinez",
      email: "mia.martinez@example.com",
      id: "kygsqwrxrareax5jiem7xd",
      job: "Engineer",
      initials: "MM",
      department: "R&D",
      workphone: "01724989441",
      mobile: "01724619791",
      manager: "olivia.b@megazap.us",
      employeeid: "77",
      costcenter: "96",
      buildingid: "124",
      floorname: "PQR",
      floorsection: "central area",
      location: "112 ABC",
      address: "606 Redwood Boulevard",
      image: "https://example.com/image8.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1999-02-20",
      DOJ: "2020-12-29",
      CF1: "IT",
      firstName: "Lucas",
      lastName: "Brown",
      name: "Lucas Brown",
      email: "lucas.brown@example.com",
      id: "pm1sfenuy7brh5jxnz7hxr",
      job: "Product Manager",
      initials: "LB",
      department: "Engineering",
      workphone: "01724331249",
      mobile: "01724352734",
      manager: "michael.s@megazap.us",
      employeeid: "42",
      costcenter: "44",
      buildingid: "117",
      floorname: "YZ",
      floorsection: "west area",
      location: "117 PQR",
      address: "303 Cedar Avenue",
      image: "https://example.com/image7.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1994-02-19",
      DOJ: "2023-07-30",
      CF1: "Product",
      firstName: "John",
      lastName: "Brown",
      name: "John Brown",
      email: "john.brown@example.com",
      id: "1z7ibh3zmaagslh7febppd",
      job: "Operations Manager",
      initials: "JB",
      department: "HR",
      workphone: "01724276522",
      mobile: "01724534365",
      manager: "james.j@megazap.us",
      employeeid: "98",
      costcenter: "36",
      buildingid: "129",
      floorname: "JKL",
      floorsection: "central area",
      location: "117 PQR",
      address: "808 Ash Avenue",
      image: "https://example.com/image2.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1993-03-29",
      DOJ: "2022-03-10",
      CF1: "Customer Support",
      firstName: "Charlotte",
      lastName: "Miller",
      name: "Charlotte Miller",
      email: "charlotte.miller@example.com",
      id: "ideo66uvaybx3xjv2h6yt",
      job: "IT Support Specialist",
      initials: "CM",
      department: "HR",
      workphone: "01724505215",
      mobile: "01724353974",
      manager: "olivia.b@megazap.us",
      employeeid: "39",
      costcenter: "60",
      buildingid: "121",
      floorname: "PQR",
      floorsection: "east wing",
      location: "114 GHI",
      address: "404 Willow Street",
      image: "https://example.com/image9.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
    {
      DOB: "1971-03-30",
      DOJ: "2017-06-28",
      CF1: "HR",
      firstName: "Charlotte",
      lastName: "Lee",
      name: "Charlotte Lee",
      email: "charlotte.lee@example.com",
      id: "zp4cvb70qdr76rngggt3wc",
      job: "Marketing Specialist",
      initials: "CL",
      department: "Legal",
      workphone: "01724886318",
      mobile: "01724548479",
      manager: "john.d@megazap.us",
      employeeid: "56",
      costcenter: "40",
      buildingid: "119",
      floorname: "MNO",
      floorsection: "east wing",
      location: "121 ABC",
      address: "404 Willow Street",
      image: "https://example.com/image2.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1988-02-26",
      DOJ: "2019-06-29",
      CF1: "Finance",
      firstName: "Charlotte",
      lastName: "Smith",
      name: "Charlotte Smith",
      email: "charlotte.smith@example.com",
      id: "5lp8l67xqa46fkui9hvly",
      job: "Operations Manager",
      initials: "CS",
      department: "Customer Support",
      workphone: "01724956601",
      mobile: "01724653719",
      manager: "john.d@megazap.us",
      employeeid: "38",
      costcenter: "78",
      buildingid: "123",
      floorname: "DEF",
      floorsection: "east wing",
      location: "115 JKL",
      address: "456 Oak Avenue",
      image: "https://example.com/image6.jpg",
      gender: "Male",
      employmentType: "Part-Time",
    },
    {
      DOB: "1981-08-12",
      DOJ: "2015-03-07",
      CF1: "Sales",
      firstName: "Mia",
      lastName: "Williams",
      name: "Mia Williams",
      email: "mia.williams@example.com",
      id: "04i7xedtcp6fhk0c3qyunew",
      job: "Operations Manager",
      initials: "MW",
      department: "Finance",
      workphone: "01724917545",
      mobile: "01724434747",
      manager: "olivia.b@megazap.us",
      employeeid: "79",
      costcenter: "28",
      buildingid: "125",
      floorname: "YZ",
      floorsection: "central area",
      location: "121 ABC",
      address: "303 Cedar Avenue",
      image: "https://example.com/image7.jpg",
      gender: "Male",
      employmentType: "Full-Time",
    },
    {
      DOB: "1983-08-03",
      DOJ: "2021-05-24",
      CF1: "Engineering",
      firstName: "Olivia",
      lastName: "Martinez",
      name: "Olivia Martinez",
      email: "olivia.martinez@example.com",
      id: "mqtyym2peaoedb35fqbnr",
      job: "Research Analyst",
      initials: "OM",
      department: "Legal",
      workphone: "01724541486",
      mobile: "01724885631",
      manager: "michael.s@megazap.us",
      employeeid: "53",
      costcenter: "81",
      buildingid: "112",
      floorname: "PQR",
      floorsection: "south area",
      location: "117 PQR",
      address: "123 Elm Street",
      image: "https://example.com/image11.jpg",
      gender: "Male",
      employmentType: "Temporary",
    },
    {
      DOB: "1986-12-31",
      DOJ: "2016-12-14",
      CF1: "IT",
      firstName: "Mia",
      lastName: "Davis",
      name: "Mia Davis",
      email: "mia.davis@example.com",
      id: "6ndvp6smwu5jipnxi3lm8",
      job: "HR Manager",
      initials: "MD",
      department: "Product",
      workphone: "01724625599",
      mobile: "01724233322",
      manager: "james.j@megazap.us",
      employeeid: "83",
      costcenter: "81",
      buildingid: "110",
      floorname: "GHI",
      floorsection: "north wing",
      location: "112 ABC",
      address: "789 Pine Road",
      image: "https://example.com/image5.jpg",
      gender: "Female",
      employmentType: "Temporary",
    },
  ];